#!/usr/bin/env python3
# read spec
#  parse arguments
#  locate relevant files
#  concatenate spec and parameter files
#  get AST via Conjure
# benchmark performance
#  time running conjure solve
# apply rewriting
#  call rewriting system with specified rewrite
#  check rewrite actually made a change
# if rewrite happened, benchmark performance of new spec
#  concatenate spec and parameter files
# report comparison

import sys
import argparse
p = argparse.ArgumentParser()
p.add_argument('-s', '--spec', action='store')
p.add_argument('-p', '--param', action='store')
p.add_argument('-r', '--rewrite', action='store')
args = p.parse_args(args=sys.argv[1:])
# args.spec is the input spec filename
# args.param is the input param filename
# args.rewrite is the kind of rewrite to perform
print(args.spec, args.param, args.rewrite)

import pathlib
from pathlib import Path
specfile = Path(args.spec)
paramfile = Path(args.param)
if specfile.is_file():
    print('found spec file', specfile)
if paramfile.is_file():
    print('found param file', paramfile)

